-- MySQL Script generated by MySQL Workbench
-- 12/01/15 02:15:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema social_network
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `social_network` ;

-- -----------------------------------------------------
-- Schema social_network
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `social_network` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `social_network` ;

-- -----------------------------------------------------
-- Table `social_network`.`UserRole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_network`.`UserRole` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `social_network`.`UserRole` (
  `role_id` INT NOT NULL COMMENT '',
  `role_name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`role_id`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `social_network`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_network`.`User` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `social_network`.`User` (
  `user_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `password` VARCHAR(100) NOT NULL COMMENT '',
  `role` INT NOT NULL COMMENT '',
  `manager` INT NULL COMMENT '',
  PRIMARY KEY (`user_id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `social_network`.`UserInfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_network`.`UserInfo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `social_network`.`UserInfo` (
  `info_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `surname` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `birthday` DATE NULL DEFAULT NULL COMMENT '',
  `photo` VARCHAR(2083) NULL DEFAULT NULL COMMENT '',
  `user_id` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`info_id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `social_network`.`SessionHistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_network`.`SessionHistory` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `social_network`.`SessionHistory` (
  `idSessionHistory` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `date` TIMESTAMP(6) NOT NULL COMMENT '',
  `user` INT NOT NULL COMMENT '',
  `ip_address` VARCHAR(45) NOT NULL COMMENT '',
  `brouser_type` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idSessionHistory`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `social_network`.`Status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_network`.`Status` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `social_network`.`Status` (
  `status_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `statusName` VARCHAR(45) NOT NULL COMMENT '',
  `type` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`status_id`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `social_network`.`File`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_network`.`File` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `social_network`.`File` (
  `idFile` INT NOT NULL COMMENT '',
  `fileName` VARCHAR(45) NULL COMMENT '',
  `pathToFile` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`idFile`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `social_network`.`Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_network`.`Comment` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `social_network`.`Comment` (
  `idComment` INT NOT NULL COMMENT '',
  `text` TEXT(1000) NULL COMMENT '',
  `date_created` TIMESTAMP(6) NULL COMMENT '',
  `date_updated` TIMESTAMP(6) NULL COMMENT '',
  `deleted` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`idComment`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `social_network`.`User_File`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_network`.`User_File` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `social_network`.`User_File` (
  `User_user_id` INT NOT NULL COMMENT '',
  `File_idFile` INT NOT NULL COMMENT '',
  PRIMARY KEY (`User_user_id`, `File_idFile`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `social_network`.`Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_network`.`Project` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `social_network`.`Project` (
  `project_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `status` INT NOT NULL COMMENT '',
  `parrent_project` INT NULL COMMENT '',
  `description` VARCHAR(1000) NULL COMMENT '',
  `date_created` TIMESTAMP(6) NULL COMMENT '',
  `date_updated` TIMESTAMP(6) NULL COMMENT '',
  `responsible` INT NOT NULL COMMENT '',
  PRIMARY KEY (`project_id`)  COMMENT '')
  parrent_project INT FOREIGN KEY REFERENCES Book(Pk_Book_Id)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `social_network`.`Task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_network`.`Task` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `social_network`.`Task` (
  `task_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `date_created` TIMESTAMP(6) NULL COMMENT '',
  `date_updated` TIMESTAMP(6) NULL COMMENT '',
  `deleted` TINYINT(1) NULL COMMENT '',
  `responsible` INT(11) NULL COMMENT '',
  `project` INT NOT NULL COMMENT '',
  `status` INT NOT NULL COMMENT '',
  PRIMARY KEY (`task_id`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `social_network`.`Comment_Task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_network`.`Comment_Task` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `social_network`.`Comment_Task` (
  `Comment_idComment` INT NOT NULL COMMENT '',
  `Task_task_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Comment_idComment`, `Task_task_id`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `social_network`.`File_Task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_network`.`File_Task` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `social_network`.`File_Task` (
  `File_idFile` INT NOT NULL COMMENT '',
  `Task_task_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`File_idFile`, `Task_task_id`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `social_network`.`Comment_Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_network`.`Comment_Project` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `social_network`.`Comment_Project` (
  `comment_id` INT NOT NULL COMMENT '',
  `project_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`comment_id`, `project_id`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `social_network`.`User_Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_network`.`User_Comment` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `social_network`.`User_Comment` (
  `User_user_id` INT NOT NULL COMMENT '',
  `Comment_idComment` INT NOT NULL COMMENT '',
  PRIMARY KEY (`User_user_id`, `Comment_idComment`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
