-- MySQL Script generated by MySQL Workbench
-- 11/27/15 13:04:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema social_network
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `social_network` ;

-- -----------------------------------------------------
-- Schema social_network
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `social_network` DEFAULT CHARACTER SET utf8 ;
USE `social_network` ;

-- -----------------------------------------------------
-- Table `social_network`.`UserRole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_network`.`UserRole` ;

CREATE TABLE IF NOT EXISTS `social_network`.`UserRole` (
  `role_id` INT NOT NULL COMMENT '',
  `role_name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`role_id`)  COMMENT '')
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_network`.`User` ;

CREATE TABLE IF NOT EXISTS `social_network`.`User` (
  `user_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `email` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `password` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `role` INT NOT NULL COMMENT '',
  `manager` INT NULL COMMENT '',
  PRIMARY KEY (`user_id`, `role`)  COMMENT '',
  INDEX `fk_User_UserRole1_idx` (`role` ASC)  COMMENT '',
  INDEX `fk_User_User1_idx` (`manager` ASC)  COMMENT '',
  CONSTRAINT `fk_User_UserRole1`
  FOREIGN KEY (`role`)
  REFERENCES `social_network`.`UserRole` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_User1`
  FOREIGN KEY (`manager`)
  REFERENCES `social_network`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB
  AUTO_INCREMENT = 15
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `social_network`.`UserInfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_network`.`UserInfo` ;

CREATE TABLE IF NOT EXISTS `social_network`.`UserInfo` (
  `info_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `surname` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `birthday` DATE NULL DEFAULT NULL COMMENT '',
  `position` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `photo` VARCHAR(2083) NULL DEFAULT NULL COMMENT '',
  `user_id` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`info_id`)  COMMENT '',
  INDEX `user_id` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `userinfo_ibfk_1`
  FOREIGN KEY (`user_id`)
  REFERENCES `social_network`.`User` (`user_id`))
  ENGINE = InnoDB
  AUTO_INCREMENT = 5
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `social_network`.`SessionHistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_network`.`SessionHistory` ;

CREATE TABLE IF NOT EXISTS `social_network`.`SessionHistory` (
  `idSessionHistory` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `date` TIMESTAMP(6) NOT NULL COMMENT '',
  `user` INT NOT NULL COMMENT '',
  `ip_address` VARCHAR(45) NOT NULL COMMENT '',
  `brouser_type` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idSessionHistory`)  COMMENT '',
  INDEX `fk_SessionHistory_user1_idx` (`user` ASC)  COMMENT '',
  CONSTRAINT `fk_SessionHistory_user1`
  FOREIGN KEY (`user`)
  REFERENCES `social_network`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`Status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_network`.`Status` ;

CREATE TABLE IF NOT EXISTS `social_network`.`Status` (
  `status_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `statusName` VARCHAR(45) NOT NULL COMMENT '',
  `type` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`status_id`)  COMMENT '')
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`File`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_network`.`File` ;

CREATE TABLE IF NOT EXISTS `social_network`.`File` (
  `idFile` INT NOT NULL COMMENT '',
  `fileName` VARCHAR(45) NULL COMMENT '',
  `pathToFile` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`idFile`)  COMMENT '')
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_network`.`Comment` ;

CREATE TABLE IF NOT EXISTS `social_network`.`Comment` (
  `idComment` INT NOT NULL COMMENT '',
  `text` TEXT(1000) NULL COMMENT '',
  `date_created` TIMESTAMP(6) NULL COMMENT '',
  `date_updated` TIMESTAMP(6) NULL COMMENT '',
  `deleted` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`idComment`)  COMMENT '')
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`User_File`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_network`.`User_File` ;

CREATE TABLE IF NOT EXISTS `social_network`.`User_File` (
  `User_user_id` INT NOT NULL COMMENT '',
  `File_idFile` INT NOT NULL COMMENT '',
  PRIMARY KEY (`User_user_id`, `File_idFile`)  COMMENT '',
  INDEX `fk_User_has_File_File1_idx` (`File_idFile` ASC)  COMMENT '',
  INDEX `fk_User_has_File_User1_idx` (`User_user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_User_has_File_User1`
  FOREIGN KEY (`User_user_id`)
  REFERENCES `social_network`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_File_File1`
  FOREIGN KEY (`File_idFile`)
  REFERENCES `social_network`.`File` (`idFile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `social_network`.`Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_network`.`Project` ;

CREATE TABLE IF NOT EXISTS `social_network`.`Project` (
  `project_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `status` INT NOT NULL COMMENT '',
  `parrent_project` INT NULL COMMENT '',
  `description` VARCHAR(1000) NULL COMMENT '',
  `date_created` TIMESTAMP(6) NULL COMMENT '',
  `date_updated` TIMESTAMP(6) NULL COMMENT '',
  `responsible` INT NOT NULL COMMENT '',
  PRIMARY KEY (`project_id`)  COMMENT '',
  INDEX `fk_Project_Project1_idx` (`parrent_project` ASC)  COMMENT '',
  INDEX `fk_Project_Status1_idx` (`status` ASC)  COMMENT '',
  INDEX `fk_Project_User1_idx` (`responsible` ASC)  COMMENT '',
  CONSTRAINT `fk_Project_Project1`
  FOREIGN KEY (`parrent_project`)
  REFERENCES `social_network`.`Project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Project_Status1`
  FOREIGN KEY (`status`)
  REFERENCES `social_network`.`Status` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Project_User1`
  FOREIGN KEY (`responsible`)
  REFERENCES `social_network`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`Task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_network`.`Task` ;

CREATE TABLE IF NOT EXISTS `social_network`.`Task` (
  `task_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `date_created` TIMESTAMP(6) NULL COMMENT '',
  `date_updated` TIMESTAMP(6) NULL COMMENT '',
  `deleted` TINYINT(1) NULL COMMENT '',
  `responsible` INT(11) NULL COMMENT '',
  `project` INT NOT NULL COMMENT '',
  `status` INT NOT NULL COMMENT '',
  PRIMARY KEY (`task_id`)  COMMENT '',
  INDEX `fk_Task_User1_idx` (`responsible` ASC)  COMMENT '',
  INDEX `fk_Task_Project1_idx` (`project` ASC)  COMMENT '',
  INDEX `fk_Task_Status1_idx` (`status` ASC)  COMMENT '',
  CONSTRAINT `fk_Task_User1`
  FOREIGN KEY (`responsible`)
  REFERENCES `social_network`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Task_Project1`
  FOREIGN KEY (`project`)
  REFERENCES `social_network`.`Project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Task_Status1`
  FOREIGN KEY (`status`)
  REFERENCES `social_network`.`Status` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`Comment_Task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_network`.`Comment_Task` ;

CREATE TABLE IF NOT EXISTS `social_network`.`Comment_Task` (
  `Comment_idComment` INT NOT NULL COMMENT '',
  `Task_task_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Comment_idComment`, `Task_task_id`)  COMMENT '',
  INDEX `fk_Comment_has_Task_Task1_idx` (`Task_task_id` ASC)  COMMENT '',
  INDEX `fk_Comment_has_Task_Comment1_idx` (`Comment_idComment` ASC)  COMMENT '',
  CONSTRAINT `fk_Comment_has_Task_Comment1`
  FOREIGN KEY (`Comment_idComment`)
  REFERENCES `social_network`.`Comment` (`idComment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_has_Task_Task1`
  FOREIGN KEY (`Task_task_id`)
  REFERENCES `social_network`.`Task` (`task_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`File_Task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_network`.`File_Task` ;

CREATE TABLE IF NOT EXISTS `social_network`.`File_Task` (
  `File_idFile` INT NOT NULL COMMENT '',
  `Task_task_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`File_idFile`, `Task_task_id`)  COMMENT '',
  INDEX `fk_File_has_Task_Task1_idx` (`Task_task_id` ASC)  COMMENT '',
  INDEX `fk_File_has_Task_File1_idx` (`File_idFile` ASC)  COMMENT '',
  CONSTRAINT `fk_File_has_Task_File1`
  FOREIGN KEY (`File_idFile`)
  REFERENCES `social_network`.`File` (`idFile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_File_has_Task_Task1`
  FOREIGN KEY (`Task_task_id`)
  REFERENCES `social_network`.`Task` (`task_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`Comment_Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_network`.`Comment_Project` ;

CREATE TABLE IF NOT EXISTS `social_network`.`Comment_Project` (
  `comment_id` INT NOT NULL COMMENT '',
  `project_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`comment_id`, `project_id`)  COMMENT '',
  INDEX `fk_Comment_has_Project_Project1_idx` (`project_id` ASC)  COMMENT '',
  INDEX `fk_Comment_has_Project_Comment1_idx` (`comment_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Comment_has_Project_Comment1`
  FOREIGN KEY (`comment_id`)
  REFERENCES `social_network`.`Comment` (`idComment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_has_Project_Project1`
  FOREIGN KEY (`project_id`)
  REFERENCES `social_network`.`Project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_network`.`User_Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `social_network`.`User_Comment` ;

CREATE TABLE IF NOT EXISTS `social_network`.`User_Comment` (
  `User_user_id` INT NOT NULL COMMENT '',
  `Comment_idComment` INT NOT NULL COMMENT '',
  PRIMARY KEY (`User_user_id`, `Comment_idComment`)  COMMENT '',
  INDEX `fk_User_has_Comment_Comment1_idx` (`Comment_idComment` ASC)  COMMENT '',
  INDEX `fk_User_has_Comment_User1_idx` (`User_user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_User_has_Comment_User1`
  FOREIGN KEY (`User_user_id`)
  REFERENCES `social_network`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Comment_Comment1`
  FOREIGN KEY (`Comment_idComment`)
  REFERENCES `social_network`.`Comment` (`idComment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
