language: java
jdk:
  - oraclejdk8
script:
        - mvn pmd:cpd-check
        - mvn test
instal: mvn install

notifications:
  email:
    recipients:
      - kuzmenko.volodimir@gmail.com 
      - zakolenkoroman@gmail.com
    on_success: always
    on_failure: always